### ISSUE TITLE
Seems to clash with YT plugin

### ISSUE THREAD

**Issue by b-risk** [Tsunami014/My-Grayjay-plugin#3]
I'm not entirely sure if this is a problem within the YT Music source itself (which is why I didn't tag as a bug but you can change it later), but through the home tab if you click on one from the YT Music source well the YT source is enabled it will give an error saying the YouTube source cannot access non-whitelisted URL, but disabling the YT source fixes this which is why I'm unsure if it's caused by this source, the reason I am posting this is to let you know and you might need to contact Futo or make a bug report if you can't fix this issue with your source.

Edit: Seemed to be an issue with the priority? Pretty weird but I put the YT Music source above the normal YT one and it seemed to fix it. Feel free to close this issue.
BTW, you should change the name of this Repo so more people can find it.

**Comment by Tsunami014** [comment]
Yes this is a known issue, I told FUTO about it and they say we should just change the YouTube one to include YouTube music website and that'll work but I spent so long on this and I also think that a separate plugin for YouTube music would be better than just adding more parameters to the base YouTube one (it already has too many) 

And I should change the name of this repo, every since I started working on it I thought it was a bad name but I never was bothered to do so (I will try soon)

**Comment by Tsunami014** [comment]
So if anyone has this issue then just reorder the plugins and it'll be fine

**Comment by b-risk** [comment]
> Yes this is a known issue, I told FUTO about it and they say we should just change the YouTube one to include YouTube music website and that'll work but I spent so long on this and I also think that a separate plugin for YouTube music would be better than just adding more parameters to the base YouTube one (it already has too many)
> 
> And I should change the name of this repo, every since I started working on it I thought it was a bad name but I never was bothered to do so (I will try soon)

I agree with you, YT music is different enough of a platform, even though it technically runs the same site. Perhaps ask if they will include your source or code from it if you add it to a pull request?
